### ISSUE TITLE
作者有没有兴趣互相加个友情链接

### ISSUE THREAD

**Issue by zxwk1998** [vue3/vue3-News#19]
https://github.com/chuzhixin/vue-admin-beautiful
![image](https://user-images.githubusercontent.com/26647258/90981512-0e88fa80-e594-11ea-9130-46a7d9b6bbbd.png)

**Comment by bluezhan** [comment]
不好意思，才回来看到。
可以的，看了你的项目非常不错。
这里借问一下，什么时候升级为vue3?

**Comment by chuzhixin** [comment]
得看element的进度了 如果他后期不支持那我只能换底层框架了 明天我先加上你的链接

**Comment by bluezhan** [comment]
> 得看element的进度了 如果他后期不支持那我只能换底层框架了 明天我先加上你的链接

ok, got it, 那挺被动的；我这几天会把你的链接添加上去。
