### ISSUE TITLE
Element UI 升级 Vue 3.0 描述可能有误

### ISSUE THREAD

**Issue by xxyuk** [vue3/vue3-News#20]
Element UI 的官方 Vue 3.0 升级版应该是这个 Element Plus 仓库 https://github.com/element-plus/element-plus， 我看目前进度已经升级的差不多完成了。

而 Readme 里面写的 kkb 那个据我所知只是一个培训班的作品，看issue 整个项目还在很初期，让他们的学生认领，至于里面为啥有500多个贡献者 只是因为似乎他把老仓库直接复制过来了，容易给人误导

**Comment by bluezhan** [comment]
got it
