### ISSUE TITLE
I found this on NewsBreak: Infant shot, 2 adults dead in house shooting 

### ISSUE THREAD

**Issue by ghost** [vue3/vue3-News#29]
I found this on NewsBreak: Infant shot, 2 adults dead in house shooting 
https://share.newsbreak.com/30gwglkq       look yall are gonna quit playing with me fr like im fucking retarted yall are for continuously testing me

**Comment by ChanningHan** [comment]
你好，我是韩沅霖，感谢你发来的邮件，我已收到并会尽快查看，辛苦了！若有急事，烦请电联或发送短信。祝您工作顺利，生活愉快！

**Comment by UserHuRu** [comment]
邮件已成功收到啦～胡茹茹
